linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
    - "Gemfile.lock"
    - "test/*"
    - "node_modules/*"
    - "app/channels*"
    - "app/helpers/*"
    - "app/jobs/*"
    - "app/mailers/*"
    - "app/models/*"
    - "config/environment.rb"
    - "config/boot.rb"
    - "config/application.rb"
    - "config/puma.rb"
